<?php namespace Laradic\Docit\Providers;

#use Debugger;
use Illuminate\Contracts\Config\Repository;
use Illuminate\Routing\Router;
use Illuminate\Foundation\Support\Providers\RouteServiceProvider as BaseServiceProvider;
use View;

class RouteServiceProvider extends BaseServiceProvider {

	/**
	 * This namespace is applied to the controller routes in your routes file.
	 *
	 * In addition, it is set as the URL generator's root namespace.
	 *
	 * @var string
	 */
	protected $namespace = 'Laradic\Docit\Http\Controllers';

	/**
	 * @var \Illuminate\Contracts\Config\Repository
	 */
	protected $config;

	public function __construct($app)
	{
		parent::__construct($app); // TODO: Change the autogenerated stub
		$this->config = $app['config'];
	}


	/**
	 * Define your route model bindings, pattern filters, etc.
	 *
	 * @param  \Illuminate\Routing\Router  $router
	 * @return void
	 */
	public function boot(Router $router)
	{
		parent::boot($router);

	}

	/**
	 * Define the routes for the application.
	 *
	 * @param  \Illuminate\Routing\Router  $router
	 * @return void
	 */
	public function map(Router $router)
	{
		$router->group(['prefix' => $this->config->get('laradic/docit::base_route'), 'namespace' => $this->namespace], function($router)
		{
			require __DIR__ . '/../Http/routes.php';
		});
	}

}
